name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        run: |
          sudo apt-get -y install tree
          dev/lint-shellcheck
      - uses: terraform-linters/setup-tflint@v3
      - name: tflint
        run: dev/lint
